### ISSUE TITLE
MappingGeneratorRefactoring error

### ISSUE THREAD

**Issue by jsodeman** [cezarypiatek/MappingGeneratorIssueTracker#21]
I'm getting an error trying to generate a method mapping.

VS 2022 v17.5.3
MappingGenerator 2023.3.55
R# 2022.3.3

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at MappingGenerator.VS2019Features.ReflectionNullabilityResolver.StripNullability(ITypeSymbol type)
   at MappingGenerator.Mappings.MappingContext.GetTypeExpression(String fullyQualifiedMetadataName)
   at MappingGenerator.Mappings.Converters.FromStringConverter.Initializer(MappingContext context)
   at MappingGenerator.Mappings.Converters.FromStringConverter.CreateConversion(SourceMappingElement source,AnnotatedType targetType,MappingContext mappingContext,MappingPath mappingPath,Boolean allowForCustomConversions,Boolean rootMapping)
   at MappingGenerator.Mappings.Converters.FirstWorkingConverter.CreateConversion(SourceMappingElement source,AnnotatedType targetType,MappingContext mappingContext,MappingPath mappingPath,Boolean allowForCustomConversions,Boolean rootMapping)
   at MappingGenerator.Mappings.Converters.NullableToNotNullExpressionConverterDecorator.CreateConversion(SourceMappingElement source,AnnotatedType targetType,MappingContext mappingContext,MappingPath mappingPath,Boolean allowForCustomConversions,Boolean rootMapping)
   at MappingGenerator.Mappings.MappingEngine.MapExpression(SourceMappingElement source,AnnotatedType targetType,MappingContext mappingContext,MappingPath mappingPath,Boolean allowForCustomConversions,Boolean rootMapping)
   at MappingGenerator.Mappings.MappingImplementors.SingleParameterPureMappingMethodImplementor.GenerateImplementation(IMethodSymbol methodSymbol,SemanticModel semanticModel,MappingContext mappingContext,MappingSourceHint hint)
   at MappingGenerator.Mappings.MappingImplementorEngine.GenerateMappingStatements(IMethodSymbol methodSymbol,SemanticModel semanticModel,MappingContext mappingContext,IMappingMethodImplementor mappingMethodImplementor)
   at MappingGenerator.Mappings.MappingImplementorEngine.GenerateMappingBlock(IMethodSymbol methodSymbol,SemanticModel semanticModel,MappingContext mappingContext,IMappingMethodImplementor mappingMethodImplementor)
   at async MappingGenerator.Features.Refactorings.Mappings.MappingMethod.MappingGeneratorRefactoring.GenerateMappingMethodBodyCustom(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async MappingGenerator.Features.Refactorings.Mappings.MappingMethod.MappingGeneratorRefactoring.<>c__DisplayClass14_0.<TryToRegisterRefactoring>b__0(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.PreviewChangesSuggestedAction.CreateAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.GetPreviewChangesFlavorAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.CreateAllFlavorsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

![image](https://user-images.githubusercontent.com/2388842/227986751-df4276ad-21a5-43b4-a68e-57e63bec44ed.png)

![image](https://user-images.githubusercontent.com/2388842/227986901-d6097a48-c632-4ca6-938d-ab56b5782b4e.png)

**Comment by jsodeman** [comment]
After selecting Enable I am able to creating the mapping, though it takes hitting Ctr-. twice to get the Generate prompts.

**Comment by cezarypiatek** [comment]
Thanks for reporting this issue.

Can you share the definition of source and target types? Or at least try to isolate the property causing this issue. I will be grateful for help with narrowing down the source of that problem.

**Comment by jsodeman** [comment]
```
	public class ProductionTask
	{
		public int Id { get; set; }
		public string Category { get; set; }
		public string Topic { get; set; }
		public string AgentFileId { get; set; }
		public string FileNumber { get; set; }
		public string FileId { get; set; }
		public string AssignedTo { get; set; }
		public string Status { get; set; }
		public DateTime? StartDateTime { get; set; }
		public DateTime? EndDateTime { get; set; }
		public DateTime? DueDateTime { get; set; }
	}

	public class ProductionTaskAddRequest {
		public string Category { get; set; }
		public string Topic { get; set; }
		public string AgentFileId { get; set; }
		public string FileNumber { get; set; }
		public string FileId { get; set; }
		public string AssignedTo { get; set; }
	}

**Comment by cezarypiatek** [comment]
One more question: what version of dotnet framework is used in your project?

**Comment by jsodeman** [comment]
Net 4.8

**Comment by cezarypiatek** [comment]
Thanks, I think I found the culprit.  I will try to release the fix tomorrow.

**Comment by cezarypiatek** [comment]
Please try to update to v2023.3.56 and let me know it the issue is gone.

**Comment by jsodeman** [comment]
I updated to the new version and the issue is gone. Thank you for the fast fix.
