### ISSUE TITLE
latest version throwing exception 

### ISSUE THREAD

**Issue by kmvickers** [cezarypiatek/MappingGeneratorIssueTracker#26]
latest VSand MG is throwing exception every time i try to use

System.ArgumentException : The node is not part of the tree.
Parameter name: node
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.CheckNodeInOriginalTree(SyntaxNode node)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.InsertAfter(SyntaxNode node,IEnumerable`1 newNodes)
   at async MappingGenerator.Features.Refactorings.Mappings.MappingMethod.MappingGeneratorRefactoring.GenerateMappingMethodBodyCustom(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async MappingGenerator.Features.Refactorings.Mappings.MappingMethod.MappingGeneratorRefactoring.<>c__DisplayClass14_0.<TryToRegisterRefactoring>b__0(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputePreviewOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass16_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)

**Comment by cezarypiatek** [comment]
Please provide a code example on which you are trigerring MappingGenerator action

**Comment by kmvickers** [comment]
what do you want? the model it is generating for ?

**Comment by cezarypiatek** [comment]
yes, the definitions of source and target types
